name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code
      - name: Insert token
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $DATA > ~/work/urban-huikka/urban-huikka/app/google-services.json
      - uses: actions/setup-java@v3
        name: Set up JDK
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Run Lint
        run: ./gradlew lintDebug
      - name: Upload Lint report
        uses: actions/upload-artifact@v3
        with:
          name: lint_report
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code
      - name: Insert token
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $DATA > ~/work/urban-huikka/urban-huikka/app/google-services.json
      - uses: actions/setup-java@v3
        name: Configure Java version
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Unit tests
        run: ./gradlew test
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [unit-test]
    name: Instrumentation tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code
      - name: Insert token
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $DATA > ~/work/urban-huikka/urban-huikka/app/google-services.json
      - uses: actions/setup-java@v3
        name: Configure Java version
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/

  package:
    needs: [instrumentation-test]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code
      - name: Insert token
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $DATA > ~/work/urban-huikka/urban-huikka/app/google-services.json
      - uses: actions/setup-java@v3
        name: Configure Java version
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: urban-huikka.apk
          path: app/build/outputs/apk/debug/app-debug.apk