name: CI

on:
  push:

jobs:
  build:
      name: Build
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v3
          name: Checkout the code
        - name: Run init script
          run: bash ~/actions-data/init.sh
        - uses: actions/setup-java@v3
          name: Set up JDK 17
          with:
            distribution: 'temurin'
            java-version: '17'
        - name: Setup Android SDK
          uses: amyu/setup-android@v2
          with:
            sdk-version: '33'  
            generate-job-summary: false
        - name: Build with gradle
          run: ./gradlew build

  lint:
    name: Lint
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Setup Android SDK
        uses: amyu/setup-android@v2
        with:
          sdk-version: '33'  
          generate-job-summary: false
      - name: Run Lint
        run: ./gradlew lintDebug
      - name: Upload Lint report
        uses: actions/upload-artifact@v3
        with:
          name: lint_report
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [build]
    name: Unit tests
    runs-on: self-hosted
    steps:
      - name: Setup Android SDK
        uses: amyu/setup-android@v2
        with:
          sdk-version: '33'  
          generate-job-summary: false
      - name: Unit tests
        run: ./gradlew test
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [unit-test]
    name: Instrumentation tests
    runs-on: self-hosted
    steps:
      - name: Setup Android SDK
        uses: amyu/setup-android@v2
        with:
          sdk-version: '33'  
          generate-job-summary: false
      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/
          
  package:
    needs: [instrumentation-test]
    name: Generate APK
    runs-on: self-hosted
    steps:
      - name: Setup Android SDK
        uses: amyu/setup-android@v2
        with:
          sdk-version: '33'  
          generate-job-summary: false
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: urban-huikka.apk
          path: app/build/outputs/apk/debug/app-debug.apk