name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code
      - name: Create token file
        run: cat /home/runner/work/urban-huikka/urban-huikka/app/google-services.json | base64
      - name: Insert token
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $DATA > /home/runner/work/urban-huikka/urban-huikka/app/google-services.json
      - uses: actions/setup-java@v3
        name: Configure Java version
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Lint
        run: ./gradlew lintDebug
      - name: Upload Lint report
        uses: actions/upload-artifact@v3
        with:
          name: lint_report
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code
      - name: Create token file
        run: cat /home/runner/work/urban-huikka/urban-huikka/app/google-services.json | base64
      - name: Insert token
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $DATA > /home/runner/work/urban-huikka/urban-huikka/app/google-services.json
      - uses: actions/setup-java@v3
        name: Configure Java version
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Unit tests
        run: ./gradlew test
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [unit-test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code
      - name: Create token file
        run: cat /home/runner/work/urban-huikka/urban-huikka/app/google-services.json | base64
      - name: Insert token
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $DATA > /home/runner/work/urban-huikka/urban-huikka/app/google-services.json
      - uses: actions/setup-java@v3
        name: Configure Java version
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/
