name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout code files
    - name: Create token file
      run: cat /home/runner/work/urban-huikka/urban-huikka/app/google-services.json | base64
    - name: Insert token
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES }}
      run: echo $DATA > /home/runner/work/urban-huikka/urban-huikka/app/google-services.json
    - uses: actions/setup-java@v3
      name: Configure Java version
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Run Lint
      run: ./gradlew lintDebug
    - name: Upload Lint report
      uses: actions/upload-artifact@v3
      with:
        name: index.html
        path: app/build/reports/lint-results-debug.html