name: CI

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code
      - name: Run init script
        run: bash ~/actions-data/init.sh
      - uses: actions/setup-java@v3
        name: Set up JDK 17
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Lint
        run: ./gradlew lint
        continue-on-error: true
      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: lint_report
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [ lint ]
    name: Unit tests
    runs-on: self-hosted
    steps:
      - uses: actions/setup-java@v3
        name: Set up JDK 17
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Unit tests
        run: ./gradlew test
        continue-on-error: true
      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [ unit-test ]
    name: Instrumentation tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code
      - name: Insert token
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $DATA > ~/work/urban-huikka/urban-huikka/app/google-services.json
      - uses: actions/setup-java@v3
        name: Set up JDK 17
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedAndroidTest
        continue-on-error: true
      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/

  package:
    needs: [ unit-test ]
    name: Generate APK
    runs-on: self-hosted
    steps:
      - uses: actions/setup-java@v3
        name: Set up JDK 17
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: urban-huikka.apk
          path: app/build/outputs/apk/debug/app-debug.apk